### ISSUE TITLE
Are these warnings of concern for building br-base?

### ISSUE THREAD

**Issue by michael-etzkorn** [firesim/FireMarshal#205] opened 2021-08-24 17:56 UTC
```
WARNING: Unrecognized Option: version
WARNING: Unrecognized Option: sphinx
WARNING: Skipping /mnt/Vivado_part/chipyard/chipyard/software/firemarshal/.readthedocs.yaml:
WARNING: 	Missing required option 'name'
DEBUG: Loading /mnt/Vivado_part/chipyard/chipyard/software/firemarshal/marshal-config.yaml
WARNING: Unrecognized Option: board-dir
WARNING: Unrecognized Option: firesim-dir
WARNING: Skipping /mnt/Vivado_part/chipyard/chipyard/software/firemarshal/marshal-config.yaml:
WARNING: 	Missing required option 'name'
```

I'm making this a new issue since we identified where the makefile was hanging before. 

I'm running `./marshal -v -d build br-base.json # here the -d indicates --nodisk or initramfs` after setting up FireMarshal and getting these warnings at the start of the build.

**Comment by NathanTP** [comment] 2021-08-24 18:34
Yes, this is a known issue. It's a harmless erroneous warning, though annoying and unclear. What's happening is that marshal has a search path for workloads (like the $PATH variable) that includes the current directory. It tries to load some unrelated yaml files and then complains when they aren't marshal workloads. It would be solved by #149 if we ever get around to doing that since marshal would only load explicitly requested workload files.

I think I'll close this issue as a duplicate of #149 since they have the same solution.

**Closed by NathanTP** 2021-08-24 18:34 UTC
